project:
  type: website
  output-dir: docs
  
  
  
website:
  search:
    location: sidebar
    type: textbox
  bread-crumbs: false
  favicon: img/aboutme/logo.png
  title: "Jackson Strand Website"
  navbar:
    background: primary
    search: true
    logo: img/logo.png
    left:
      - text: "Work"
        file: projects.qmd
      - text: "Pics"
        menu: 
          - running.qmd
          - bugs.qmd
      - text: "test"
        file: aboutme.qmd
      - text: "CV"
        file: cv.qmd
    right: 
      - href: aboutme.qmd
        text: About Me
    tools:
      - icon: linkedin
        href: https://linkedin.com/in/jacksonstrand
      - icon: instagram
        href: https://www.instagram.com/jstrand894/
      - icon: github
        href: https://github.com/jstrand894/quarto_website
      - icon: envelope
        href: "mailto:jstrand894@gmail.com"
  sidebar:
    - title: "Work"
      style: "docked"
      search: true
      contents:
        - file: msu-masters.qmd
          contents:
            - text: "Wheat Stem Sawfly"
              href: wss.qmd
              contents:
                - text: "Controlled WSS Infestation"
                  href: pfreport.qmd
                - text: "Montana Field Sites"
                  href: fieldreport.qmd
                - text: "Organic Volatile Collection"
                  href: eag.qmds
                - text: "Weather Data"
                  href: weatherdata.qmds
              # link: weather-data.qmd
            - text: "Locoweed"
              href: locoweed-report.qmd
        - text: "Other"
          contents:
            - text: "Basketball Analysis Tool"
              file: bballref.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Jackson Strand"

format:
  html:
    theme: cosmo
    toc: false

editor: source


