project:
  type: website
  output-dir: docs
  
  
  
website:
  search:
    location: sidebar
    type: textbox
  bread-crumbs: false
  favicon: img/aboutme/logo.png
  title: "Jackson Strand"
  navbar:
    background: primary
    search: true
    logo: img/logo.png
    left:
      - text: "Work"
        file: qmd/projects.qmd
      - text: "Pics"
        menu: 
          - qmd/pics/running.qmd
          - qmd/pics/bugs.qmd
      - text: "CV"
        file: qmd/cv.qmd
    right: 
      - href: qmd/aboutme.qmd
        text: About Me
    tools:
      - icon: linkedin
        href: https://linkedin.com/in/jacksonstrand
      - icon: instagram
        href: https://www.instagram.com/jstrand894/
      - icon: github
        href: https://github.com/jstrand894/quarto_website
      - icon: envelope
        href: "mailto:jstrand894@gmail.com"
  sidebar:
    - title: "Work"
      collapse-level: 3
      border: true
      style: "docked"
      search: true
      contents:
        - text: "Projects"
          file: qmd/projects.qmd
          contents:
            - text: "MSU-Master's"
              href: qmd/projects/msu-masters.qmd
              contents:
                - text: "Wheat Stem Sawfly"
                  href: qmd/projects/msu-masters/wss.qmd
                  contents:
                  - text: "Thesis Proposal"
                    href: qmd/litreview.qmd
                  - text: "Controlled WSS Infestation"
                    href: qmd/projects/msu-masters/wss/pfreport.qmd
                  - text: "Montana Field Sites"
                    href: qmd/projects/msu-masters/wss/field_report.qmd
                  - text: "Organic Volatile Collection"
                    href: qmd/projects/msu-masters/wss/eag.qmd
                  - text: "Weather Data"
                    href: qmd/projects/msu-masters/wss/weatherdata.qmd
                - text: "Locoweed Volatiles"
                  href: qmd/projects/msu-masters/locoweed/locoweed-report.qmd
                - text: "Toadflax"
                  href: qmd/projects/msu-masters/toadflax/toadflax_report.qmd
            - text: "Other"
              contents:
                - text: "Basketball Analysis Tool"
                  file: qmd/projects/bballtool.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Jackson Strand"

format:
  html:
    theme: cosmo

editor: source


