---
title: "ndvi"
editor_options: 
  chunk_output_type: console
---

```{r library, echo = F, message = F}
library(readxl)
library(dplyr)
library(ggplot2)
library(plotly)
```

```{r read data, echo = F}
setwd("/Users/jacksonstrand/Library/CloudStorage/OneDrive-MontanaStateUniversity/GitHub/Quarto Website/Quarto Website/qmd/projects/msu/wss")

data <-
read_excel("NDVI_values_filteredx.xlsx") %>%
  dplyr::select(NDVI,date,type)
```

```{r plot, echo = F}
ggplotly(data %>%
  filter(!date %in% c("2023-03-31",
                      "2023-04-20",
                      "2023-05-10",
                      "2023-05-30",
                      "2023-06-09",
                      "2023-06-19",
                      "2023-07-14",
                      "2023-08-13")) %>%
  # mutate(NDVI = ifelse(type == "wheat", -NDVI, NDVI)) %>%
  ggplot(aes(x = date, y = NDVI, fill = type)) +
  geom_bar(stat = 'identity', 
           position = position_dodge()) +
  geom_line(stat = "smooth") +
  theme_bw()
)
```

